---
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    strategy: 
      fail-fast: false

      matrix:
        version_branch: [8]
        include:
          - version_branch: 8
            version_minor_release: 5

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Test building image
        run: docker build -t docker-rocky-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }} ./rocky${{ matrix.version_branch }}/. --build-arg VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
      
      - name: Run the built image
        run: docker run --name test-container --detach --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:ro docker-rocky-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}

      - name: Verify Ansible is accessible in the built image
        run: docker exec --tty test-container env TERM=xterm ansible --version

  tag-release:
    name: Release tags
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      packages: write

    strategy: 
      fail-fast: false

      matrix:
        version_branch: [8]
        include:
          - version_branch: 8
            version_minor_release: 5

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Add Qemu
        uses: docker/setup-qemu-action@v2

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          build-args: VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
          context: ./
          file: ./rocky${{ matrix.version_branch }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            kirillzak/docker-rocky-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}

  latest-release:
    name: Latest release
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Add Qemu
        uses: docker/setup-qemu-action@v2

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          build-args: VERSION=8.5
          context: ./
          file: ./rocky8/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            kirillzak/docker-rockry-ansible:latest
